# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False, verbose_name='编号')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='资讯标题')),
                ('href', models.CharField(blank=True, max_length=200, null=True, verbose_name='阅读地址')),
                ('pic', models.ImageField(upload_to='uploadImages', verbose_name='配图')),
            ],
            options={
                'verbose_name_plural': 'C主页资讯',
                'verbose_name': 'C主页资讯',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False, verbose_name='编号')),
                ('wxname', models.CharField(blank=True, max_length=50, null=True, verbose_name='微信名称')),
                ('wxzb', models.CharField(blank=True, max_length=200, null=True, verbose_name='文章标题')),
                ('wxsj', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('wxread', models.IntegerField(blank=True, null=True, verbose_name='阅读数')),
                ('wxhref', models.CharField(blank=True, max_length=200, null=True, verbose_name='阅读地址')),
                ('imgurl', models.CharField(blank=True, max_length=200, null=True, verbose_name='图片地址')),
                ('ispublished', models.IntegerField(choices=[(1, '发布中'), (2, '精选待发布'), (3, '精选已发布'), (0, '已发布')], verbose_name='状态')),
            ],
            options={
                'db_table': 'news',
                'verbose_name_plural': 'A微信公众号文章',
                'verbose_name': 'A微信公众号文章',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False, verbose_name='编号')),
                ('videoname', models.CharField(blank=True, max_length=200, null=True, verbose_name='视频标题')),
                ('videohref', models.CharField(blank=True, max_length=200, null=True, verbose_name='播放地址')),
            ],
            options={
                'db_table': 'video',
                'verbose_name_plural': 'B安全环保视频',
                'verbose_name': 'B安全环保视频',
            },
        ),
    ]
